
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async setTheme(setting: ThemeSetting) : Promise<ResolvedTheme> {
    return await TAURI_INVOKE("set_theme", { setting });
},
/**
 * 設定値と、それを解決した実際のテーマの両方を返す。
 * System のとき、フロントは起動直後の解決値をこれで知る。
 */
async getTheme() : Promise<ThemeStatus> {
    return await TAURI_INVOKE("get_theme");
}
}

/** user-defined events **/


export const events = __makeEvents__<{
themeChanged: ThemeChanged
}>({
themeChanged: "theme-changed"
})

/** user-defined constants **/



/** user-defined types **/

/**
 * `tauri::Theme` は specta::Type を実装せず non_exhaustive でもあるため、
 * フロントへ渡す解決済みテーマはこの型に写して扱う。
 */
export type ResolvedTheme = "light" | "dark"
export type ThemeChanged = ResolvedTheme
/**
 * `tauri::Theme` に System が無いため、OS 追従を表現するための独自設定値。
 */
export type ThemeSetting = "system" | "light" | "dark"
export type ThemeStatus = { setting: ThemeSetting; resolved: ResolvedTheme }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
